version: "3.9"

services:
  mongodb:
    image: mongo:5.0.6
    container_name: mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
  mongo-express:
    image: mongo-express:0.54.0
    container_name: mongo-express
    restart: unless-stopped
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    ports:
      - 8081:8081
    depends_on:
      - mongodb
  pythonapp:
    build:
      context: pythonapp
      dockerfile: Dockerfile
    container_name: pythonapp
    environment:
      - MONGODB_HOSTNAME=mongodb
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=password
      - WAIT_HOSTS=mongodb:27017
    depends_on:
      - mongodb

volumes:
  mongodbdata:
    driver: local
